apiVersion: platform.tfe.io/v1alpha1
kind: NamespaceClaim
metadata:
  name: ${{ values.teamName }}
  namespace: default
spec:
  teamName: ${{ values.teamName }}
  cpuQuota: "${{ values.cpuQuota }}m"
  memoryQuota: "${{ values.memoryQuota }}Gi"